### ISSUE TITLE
Typo in repository directory

### ISSUE THREAD

**Issue by IsratIJK** [FahimFBA/Efficient-Prediction-for-Alzheimers-Disease#8]
There is a typo in `Efficient-Prediction-for-Alzheimers-Disease/tree/main/Notebooks/ADNI/Complete Region of Human Brain)
/Upgraded Filder AD vs CN`

`Filter` -> `Filter`.

**Comment by FahimFBA** [comment]
Well done finding that typo!

Please resolve the issue then if you have the time. I am assigning you for this.
